### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MariusVolkhart** [mutaphore/RTSP-Client-Server#1]
Are you willing to license this source code, and if so, under which license?

**Comment by mutaphore** [comment]
Sure, I'm open to any one of the open source license (MIT, Apache, etc.). Do you have any suggestions?

**Comment by MariusVolkhart** [comment]
I'm partial to Apache 2. It's well understood and doesn't have some of the less obvious limitations that often cause developers to violate licenses like the MIT.

**Comment by mutaphore** [comment]
Done, added licensing info
