### ISSUE TITLE
FunkyServer

### ISSUE THREAD

**Issue by amthug** [mutaphore/RTSP-Client-Server#10]

**Comment by amthug** [comment]
Where to get the FunkyServer class file?

**Comment by deweistarsky** [comment]
@amthug thanks for pointing this out, I have added the FunkyServer.class file https://github.com/mutaphore/RTSP-Client-Server/blob/master/FunkyServer.class

**Comment by mutaphore** [comment]
@amthug the FunkyServer.class file has been added. Thanks for the report
