### ISSUE TITLE
When running ./run_funky it gives ClassNotFoundException

### ISSUE THREAD

**Issue by LoganWlv** [mutaphore/RTSP-Client-Server#11]
After downloading the whole repo as a .zip and building the project with make. 

Run ./run_client is **OK**
Run ./run_server is **OK**  
But run ./run_funky is **KO**

Tested on the current FunkyServer.class file in the repo.
In the readme you say to take the .class file from extract/ but where is that ?

**Comment by mutaphore** [comment]
This is fixed, the funky server binaries are now in `extras/`
