### ISSUE TITLE
Addition of another mesurement protocol

### ISSUE THREAD

**Issue by ssavva05** [mutaphore/RTSP-Client-Server#12]
Hello,
 I want to add another measurement protocol like Q4S to measure the bw latency ect and sent appropriate rate form a variety of encodings and rates from server to cient. Is this possible or I will mess it up?

**Comment by mutaphore** [comment]
This is a good idea. If you end up doing this feel free to create a PR.

**Comment by ssavva05** [comment]
Sure, but I stuck for now, because I cant find a stable documented Q4s implementation to stich it. I hope that it will be a stable q4s implementation in the future to make this possible.
