### ISSUE TITLE
Create a demo video or gif of the client GUI

### ISSUE THREAD

**Issue by mutaphore** [mutaphore/RTSP-Client-Server#2]
Need some kind of animated graphics in the README demoing the client player streaming video from server.

**Comment by NivedhithaV** [comment]
Try [Licecap](http://www.cockos.com/licecap/) to capture gifs and then add them to the README with `![Caption](username.github.com/repository/img/image.jpg)`

**Comment by ajaynataraj** [comment]
#6 
Issue can be closed
