### ISSUE TITLE
Why its taking the movie.Mjpeg file only

### ISSUE THREAD

**Issue by amit13091992** [mutaphore/RTSP-Client-Server#5]
its taking only movie.Mjpeg file only, i tried with other files with same format also but its giving error for NumberFormatException while sending video to client.
and can anyone tell me the workflow how its working and data-flow of the project.
If anyone would help that would be so greatfull. Kindly plz give a solution.
thanks in advance.

**Comment by mutaphore** [comment]
@amit13091992 can you provide stack trace or details about the error you are getting?

**Comment by sneharavi12** [comment]
I am facing the exact same issue. Although I provide the IP address that have a live video stream as the argument and the default RTSP port 554 as the arguments, it plays movie.Mjpeg.
Can't seem to figure out why.

**Comment by mutaphore** [comment]
@sneharavi12 are you using the `run_client` script to start the client side streaming? If you are, make sure to update the `FILE` variable to point to the file that you want to stream from. By default it is set to movie.Mjpeg

**Comment by sneharavi12** [comment]
Alright, at if I have to point it to a camera IP? I am interested in streaming the live video from that camera IP over RTP.

**Comment by mutaphore** [comment]
@sneharavi12 You might want to look into if your camera supports RTSP as a playback control mechanism. The server part of this repo is effectively what your camera does but it might follow a different set of commands.
