### ISSUE TITLE
Wondering if code supports files with audio?

### ISSUE THREAD

**Issue by waqasrehmance** [mutaphore/RTSP-Client-Server#7]
I have downloaded the code and tried code on mp4 videos with audio, it didn't worked. Is it possible to extend same code for mp4 videos with audio?
If support is already available but disabled please guide me how to enable it? Otherwise guide me in the direction to introduce mp4 support in your code.

**Comment by mutaphore** [comment]
@appletoeat2 this repo uses the simple Mjpeg format to demonstrate coordination between a client and server using RTSP. If you were to support MP4, I imagine you would need a tool like FFMPEG to demux the video/audio streams and pass that to the client.

If you're interested in exploring this, let me know and we could add that as a feature ticket.

**Comment by waqasrehmance** [comment]
@mutaphore Thanks for response. I am interested in working on MP4 transfer. Please let me look into FFMPEG and will sure contribute in this repository.
