### ISSUE TITLE
VLC Client

### ISSUE THREAD

**Issue by chuidiang** [mutaphore/RTSP-Client-Server#8]
Hi,

Have you tried your rtsp server with a standard rtsp client like VLC. I can't make it work.

Thank you.

**Comment by ramankeswani** [comment]
Yes please, can you let me know how can I get the rtsp link and play it on VLC

**Comment by mutaphore** [comment]
This project was intended to demonstrate the fundamental concepts of how RTSP works underneath the hood. There are probably other open source servers out there that integrates with real world clients like VLC. For now, this is out of the scope for this project.
